name: 'my first container action'
description: 'A pro tech'
author: 'jyotisable'
inputs:
  myInput:
    description: 'greeting to use'
    required: true
    default: 'Awesome beast'
outputs:
  myOutput:
    description: 'total memory'
runs:
  using: 'docker'
  image: 'Dockerfile'
